/** Top-level URLs served by `app/[section]/page.tsx`. */
export const SECTIONS = [
  'football',
  'live',
  'basketball',
  'tennis',
  'virtuals',
  'crash-games',
  'jackpot',
  'promotions',
  'help',
  'terms',
  'privacy',
  'responsible-gambling',
  'account',
  'deposit',
  'withdraw',
  'transactions',
  'login',
  'register',
  'sub-admin',
] as const
